#==============================================#
# Supply Crate by RedSMURF: Configuration file #
#==============================================#

# To add a new crate, follow the example below
# [Crate Name]
# CRATE_MODEL           =  Path of crate's model.
# CRATE_CLASS           =  0 -Ammo Crate,    1 -Grenades Crate, 2 -Market Crate.
# CRATE_MODE            = (Ammo Crate)       0 -AMMO_ONLY       1 -AMMO_VEST,      1 -AMMO_VEST,     2 -AMMO_VESTHELM,    3 -VEST_ONLY,        4 -VESTHELM_ONLY
#                       = (Grenades Crate)   0 -GRENADES_HE     1 -GRENADES_FB,    2 -GRENADES_SG,   3- GRENADES_HE_FB,   4- GRENADES_HE_SG,   5 -GRENADES_FB_SG,   6 -GRENADES_ALL
# CRATE_RATE            = -2 -Very Slow,    -1 -Slow,           0 -Normal,         1 -Fast,          2 -Very Fast
# CRATE_CAPACITY        =  Maximum amount of uses this crate can give.
# CRATE_SOUND_FLAGS     =  a -Placed Sound, b -Removed Sound,  c -Opening Sound,   d -Empty Sound,   e -Get Sound,  f -Sell Sound
# CRATE_FACTOR          =  Market price factor for Market Crates (1.0 = full price, 0.5 = half price, 2.0 = double price and so on)

# To make a crate available in the menu, you must defined at least it's name like this [Ammo Crate].
# crate model and sound cannot be changed dynamically during gameplay.

[Main Settings]
SETTING_DEFAULT_MODEL       = models/SupplyCrate/ammo_crate.mdl
SETTING_DEFAULT_CAPACITY    = 10
SETTING_DEFAULT_RATE        = 0

SETTING_SOUND_PLACED        = SupplyCrate/button4.wav
SETTING_SOUND_REMOVED       = SupplyCrate/metal6.wav
SETTING_SOUND_OPENING       = SupplyCrate/latchunlocked1.wav
SETTING_SOUND_EMPTY         = SupplyCrate/latchlocked1.wav
SETTING_SOUND_GET           = SupplyCrate/9mmclip1.wav
SETTING_SOUND_SELL          = SupplyCrate/Ch-ching.wav
SETTING_MINS_LONG           = -11.5 -21.5 -15.0
SETTING_MAXS_LONG           = 11.5 21.5 15.0
SETTING_MINS_WIDE           = -21.5 -11.5 -15.0
SETTING_MAXS_WIDE           = 21.5 11.5 15.0

SETTING_CRATE_LOAD          = 1       # Whether to load saved crates data of the current map
SETTING_CRATE_RANGE         = 65.0    # Max distance to interact with a crate.
SETTING_OFFSET_BASE         = 120.0   # Default forward offset when previewing crate placement
SETTING_OFFSET_MIN          = 65.0    # Minimum offset from the player to the crate
SETTING_OFFSET_MAX          = 250.0   # Maximum offset from the player to the crate
SETTING_OFFSET_STEP         = 10.0    # Step size when scrolling to move crate forward/backward
SETTING_OFFSET_FREQ         = 0.1     # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_ALPHA         = 90      # Transparency level of the ghost preview model (0 - 255)
SETTING_GHOST_FREQ          = 0.1     # Refresh rate of the ghost model (min = 0.1)
SETTING_REQUIRE_EMPTY       = 1       # Restrects crate use if the player's having max bp of the current weapon or a any grenade

[Ammo]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 0
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 0

[Ammo + Vest]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 1
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 0

[Fast Ammo]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 0
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 2

[Grenades HE]
CRATE_MODEL             = models/SupplyCrate/grenades_crate.mdl
CRATE_CLASS             = 1
CRATE_MODE              = 0
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 0

[Grenades ALL]
CRATE_MODEL             = models/SupplyCrate/grenades_crate.mdl
CRATE_CLASS             = 1
CRATE_MODE              = 6
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 1

[Market %25]
CRATE_MODEL             = models/SupplyCrate/weapons_crate.mdl
CRATE_CLASS             = 2
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 1
CRATE_FACTOR            = 0.25

[Market %100]
CRATE_MODEL             = models/SupplyCrate/weapons_crate.mdl
CRATE_CLASS             = 2
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdef
CRATE_RATE              = 1
CRATE_FACTOR            = 1.0
