#==============================================#
# Supply Crate by RedSMURF: Configuration file #
#==============================================#

# To add a new crate, follow the example below
# [Crate Name]
# CRATE_MODEL               = Path of crate's model
# CRATE_CLASS               = 0 - Ammo Crate,        1 - Grenades Crate,        2 - Market Crate
# CRATE_FLAGS               = a - Breaks,            b - Explodes,              c - Refill,         d - Active Delay,       e - Active Duration
# CRATE_TEAM                = 0 - Disabled           1 - Terrorist Only,        2 - CT Only,        3 - Both Teams
# CRATE_MODE                = (Armor)                a - Vest,                  b - Vesthelm
#                           = (Ammo Crate)           c - Ammo
#                           = (Grenades Crate)       c - HE,                    d - FB1,            e - FB2,                f - Smoke

# CRATE_REFILL              = Minimum - Maximum refill delay in seconds (requires flag c)
# CRATE_COOLDOWN            = Delay in seconds between each use
# CRATE_CAPACITY            = Maximum amount of supply this crate can give
# CRATE_ACTIVE_DELAY        = Minimum - Maximum delay before the crate becomes active (requires flag d)
# CRATE_ACTIVE_DURATION     = Minimum - Maximum duration of the active state (ignored if flag e is set)
# CRATE_ACTIVE_COOLDOWN     = Minimum - Maximum cooldown before reactivation

# CRATE_SPAWN_MODE          = 0 - Never              1 - Delayed                2 - Round Start
# CRATE_SPAWN               = Minimum - Maximum spawn time
# CRATE_SPAWN_CHANCE        = Crate's respawn probability (0.0 = never, 1.0 = always)

# CRATE_HEALTH              = Minimum - Maximum crate health (Default = 250)
# CRATE_ARMOR               = Minimum - Maximum crate's armor supply (Default = 100)
# CRATE_FACTOR              = Factor for Market selling and for Ammo/Grenades supplying
# CRATE_FACTOR_MAX          = Maximum factor limit for ammo crates
# CRATE_EXPLODE_DAMAGE      = Minimum - Maximum explosion damage (Default = 100 100)
# CRATE_EXPLODE_RADIUS      = Minimum - Maximum explosion radius (Default = 150 150)
# CRATE_WEAPON_MODE         = 0 - Allow all,         1 - Allow listed weapons,  2 - Block listed weapons
# CRATE_WEAPON_LIST         = List of weapons used for filtering

# To make a crate available in the menu, you must defined at least it's name like this [Ammo Crate]
# crate model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/SupplyCrate/ammo_crate.mdl
SETTING_DEFAULT_GIB             = models/metalplategibs.mdl
SETTING_DEFAULT_CLASS           = 0
SETTING_DEFAULT_FLAGS           = 0
SETTING_DEFAULT_TEAM            = 3
SETTING_DEFAULT_MODE            = c

SETTING_DEFAULT_REFILL          = 0.0 0.0
SETTING_DEFAULT_COOLDOWN        = 2.5
SETTING_DEFAULT_CAPACITY        = 10.0

SETTING_DEFAULT_SPAWN_MODE      = 1
SETTING_DEFAULT_SPAWN           = 10.0 25.0
SETTING_DEFAULT_SPAWN_CHANCE    = 1.0

SETTING_DEFAULT_ACTIVE_DELAY    = 5.0 10.0
SETTING_DEFAULT_ACTIVE_DURATION = 30.0 30.0
SETTING_DEFAULT_ACTIVE_COOLDOWN = 5.0 5.0

SETTING_DEFAULT_HEALTH          = 250.0 250.0
SETTING_DEFAULT_ARMOR           = 100 100
SETTING_DEFAULT_FACTOR          = 1.0
SETTING_DEFAULT_FACTOR_MAX      = 1.0
SETTING_DEFAULT_EXPLODE_DAMAGE  = 100.0 100.0
SETTING_DEFAULT_EXPLODE_RADIUS  = 150.0 150.0
SETTING_DEFAULT_WEAPON_MODE     = 0

SETTING_MINS                    = -17.0 -29.0 -17.0
SETTING_MAXS                    = 17.0 29.0 17.0

SETTING_CRATE_LOAD              = 1             # Whether to load saved crates data of the current map
SETTING_CRATE_RANGE             = 75.0          # Max distance to interact with a crate
SETTING_OFFSET_BASE             = 120.0         # Default forward offset when previewing crate placement
SETTING_OFFSET                  = 65.0 900.0    # Minimum - Maximum offset from the player to the crate
SETTING_OFFSET_STEP             = 10.0          # Step size when scrolling to move crate forward/backward
SETTING_OFFSET_FREQ             = 0.1           # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ              = 0.1           # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA             = 90            # Transparency level of the ghost preview model (0 - 255)

SETTING_BREAK_VELO_Z            = 7.0 12.0
SETTING_BREAK_VELO_RANDOM       = 7 12
SETTING_BREAK_COUNT             = 4 7
SETTING_BREAK_LIFE              = 10 15

SETTING_SPRITE_ZEROGXPLODE      = sprites/zerogxplode.spr
SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav

SETTING_SOUND_BUTTON4           = buttons/button4.wav
SETTING_SOUND_LOCKED            = buttons/latchlocked1.wav
SETTING_SOUND_CLIP              = items/9mmclip1.wav
SETTING_SOUND_CHCHING           = SupplyCrate/Ch-ching.wav
SETTING_SOUND_METAL             = debris/bustmetal1.wav
SETTING_SOUND_METAL             = debris/bustmetal2.wav

SETTING_COLOR_ACTIVE            = 0 255 0
SETTING_COLOR_INACTIVE          = 255 0 0

[Ammo]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = c
CRATE_CAPACITY          = 5
CRATE_FACTOR            = 0.25

[Ammo Full BP]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = c
CRATE_CAPACITY          = 5
CRATE_FACTOR            = 1.0

[Ammo & Vest]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = ac
CRATE_CAPACITY          = 5
CRATE_FACTOR            = 0.25

[Fast Ammo & High Limit]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = c
CRATE_CAPACITY          = 5
CRATE_COOLDOWN          = 0.8
CRATE_FACTOR            = 0.25
CRATE_FACTOR_MAX        = 5.0

[Grenades ALL]
CRATE_MODEL             = models/SupplyCrate/grenades_crate.mdl
CRATE_CLASS             = 1
CRATE_MODE              = bcdef
CRATE_CAPACITY          = 5

[Market Grenades]
CRATE_MODEL             = models/SupplyCrate/weapons_crate.mdl
CRATE_CLASS             = 2
CRATE_CAPACITY          = 5
CRATE_FACTOR            = 1.0
CRATE_WEAPON_MODE       = 1
CRATE_WEAPON_LIST       = 4, 9, 25

[Ammo & Break & Refill]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = c
CRATE_FLAGS             = ac
CRATE_CAPACITY          = 5
CRATE_REFILL            = 5.0 10.0
CRATE_FACTOR            = 0.25

[Grenades Explodes High Damage]
CRATE_MODEL             = models/SupplyCrate/grenades_crate.mdl
CRATE_CLASS             = 1
CRATE_MODE              = cdef
CRATE_FLAGS             = ab
CRATE_CAPACITY          = 5
CRATE_EXPLODE_DAMAGE    = 150.0 200.0
CRATE_EXPLODE_RADIUS    = 150.0 150.0

[Market Permanent Active]
CRATE_MODEL             = models/SupplyCrate/weapons_crate.mdl
CRATE_CLASS             = 2
CRATE_CAPACITY          = 5
CRATE_FACTOR            = 1.0
CRATE_FLAGS             = de
CRATE_ACTIVE_DELAY      = 10.0 15.0

[Ammo & Vesthelm CT]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = bc
CRATE_CAPACITY          = 5
CRATE_TEAM              = 2
CRATE_FACTOR            = 0.25
CRATE_FLAGS             = d
CRATE_SPAWN_MODE        = 2
CRATE_ACTIVE_DELAY      = 10.0 15.0
CRATE_ACTIVE_DURATION   = 20.0 25.0
CRATE_ACTIVE_COOLDOWN   = 10.0 10.0