#==============================================#
# Supply Crate by RedSMURF: Configuration file #
#==============================================#

# To add a new crate, follow the example below
# [Crate Name]
# CRATE_MODEL          = Path of crate's model
# CRATE_CLASS          = 0 - Ammo Crate,       1 - Grenades Crate,     2 - Market Crate
# CRATE_MODE           = (Ammo Crate)          0 - AMMO_ONLY           1 - AMMO_VEST,          2 - AMMO_VESTHELM,      3 - VEST_ONLY,          4 - VESTHELM_ONLY
#                      = (Grenades Crate)      0 - GRENADES_HE         1 - GRENADES_FB,        2 - GRENADES_SG,        3 - GRENADES_HE_FB,     4 - GRENADES_HE_SG,     5 - GRENADES_FB_SG,     6 - GRENADES_ALL
# CRATE_FLAGS          = a - Breaks,           b - Explodes
# CRATE_SOUND_FLAGS    = a - Placed Sound,     b - Using Sound,        c - Empty Sound,        d - Removed Sound,      e - Sell Sound,         f - Supply Sound,       g - Refill Sound
# CRATE_COOLDOWN       = Delay in seconds between each use
# CRATE_CAPACITY       = Maximum amount of supply this crate can give
# CRATE_REFILL         = Delay in seconds for the crate to refill, Disabled with '-1'
# CRATE_DELAY          = Seconds before the crate get activated
# CRATE_HEALTH         = Crate's health (Default = 250)
# CRATE_FACTOR         = Factor for Market selling and for Ammo supplying
# CRATE_EXPLODE_DAMAGE = Explosion Damage (Default = 100)
# CRATE_EXPLODE_RADIUS = Explosion Radius (Default = 150)

# To make a crate available in the menu, you must defined at least it's name like this [Ammo Crate]
# crate model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL       = models/SupplyCrate/ammo_crate.mdl

SETTING_MINS                = -16.0 -29.0 -17.0
SETTING_MAXS                = 16.0 29.0 17.0
SETTING_SOUND_PLACE         = SupplyCrate/button4.wav
SETTING_SOUND_REMOVE        = SupplyCrate/metal6.wav
SETTING_SOUND_EMPTY         = SupplyCrate/latchlocked1.wav
SETTING_SOUND_SUPPLY        = SupplyCrate/9mmclip1.wav
SETTING_SOUND_SELL          = SupplyCrate/Ch-ching.wav
SETTING_SOUND_REFILL        = SupplyCrate/button4.wav

SETTING_CRATE_LOAD          = 1       # Whether to load saved crates data of the current map
SETTING_REQUIRE_NEED        = 1       # Restrects crate use if the player's having max bp of the current weapon or a any grenade
SETTING_CRATE_RANGE         = 65.0    # Max distance to interact with a crate
SETTING_OFFSET_BASE         = 120.0   # Default forward offset when previewing crate placement
SETTING_OFFSET_MIN          = 65.0    # Minimum offset from the player to the crate
SETTING_OFFSET_MAX          = 900.0   # Maximum offset from the player to the crate
SETTING_OFFSET_STEP         = 10.0    # Step size when scrolling to move crate forward/backward
SETTING_OFFSET_FREQ         = 0.1     # Scroll responsivness for placement offset (lower = faster)
SETTING_GHOST_FREQ          = 0.1     # Refresh rate of the ghost model (min = 0.1)
SETTING_GHOST_ALPHA         = 90      # Transparency level of the ghost preview model (0 - 255)

[Ammo]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 0
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg

[Ammo + Vest]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 1
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg

[Fast Ammo]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 0
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg

[Grenades HE]
CRATE_MODEL             = models/SupplyCrate/grenades_crate.mdl
CRATE_CLASS             = 1
CRATE_MODE              = 0
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg

[Grenades ALL]
CRATE_MODEL             = models/SupplyCrate/grenades_crate.mdl
CRATE_CLASS             = 1
CRATE_MODE              = 6
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg

[Market %25]
CRATE_MODEL             = models/SupplyCrate/weapons_crate.mdl
CRATE_CLASS             = 2
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg
CRATE_FACTOR            = 0.25

[Market %100]
CRATE_MODEL             = models/SupplyCrate/weapons_crate.mdl
CRATE_CLASS             = 2
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg
CRATE_FACTOR            = 1.0

[Ammo BREAK & REFILL]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 0
CRATE_FLAGS             = a
CRATE_COOLDOWN          = 2.5
CRATE_CAPACITY          = 3
CRATE_SOUND_FLAGS       = abcdefg
CRATE_REFILL            = 5.0
CRATE_FACTOR            = 0.25

[Ammo EXPLODES]
CRATE_MODEL             = models/SupplyCrate/ammo_crate.mdl
CRATE_CLASS             = 0
CRATE_MODE              = 0
CRATE_FLAGS             = ab
CRATE_COOLDOWN          = 2.5
CRATE_CAPACITY          = 10
CRATE_SOUND_FLAGS       = abcdefg
CRATE_FACTOR            = 0.25



